version: "3"

services:
  algo_lib:
    build: ./algo_lib
    volumes:
      - ./algo_lib:/app
    working_dir: /app

  algo_api:
    build: ./algo_api
    volumes:
      - ./algo_api:/go/src/app
    working_dir: /go/src/app
    ports:
      - 8080:8080
