version: "3"

services:
  algo_frontend:
    container_name: frontend
    build:
      context: ./algo_frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./algo_frontend:/app
    ports:
      - 3000:3000

  algo_trader:
    container_name: trader
    build:
      context: ./algo_trader
    working_dir: /app
    volumes:
      - ./algo_trader:/app
      - ~/satoshibot/cache_binance:/data/cache_binance
    # Unit Tests
    # command: ["pytest"]
    # Backtesting
    command: ["python3", "-u", "main_test.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  algo_api:
    container_name: api
    build: ./algo_api
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=hU6GB8mupEtzgvXjrZQHKF
    volumes:
      - ./algo_api:/go/src/app
    working_dir: /go/src/app
    ports:
      - 8080:8080
    depends_on:
      - couchdb

  couchdb:
    image: couchdb:3.3.2
    container_name: couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=hU6GB8mupEtzgvXjrZQHKF
    volumes:
      - couchdb_data:/opt/couchdb/data
    ports:
      - 5984:5984

volumes:
  couchdb_data:
