version: "3"

services:
  algo_lib:
    build:
      context: ./algo_lib
    image: algo_lib_local:latest

  algo_trader:
    build:
      context: ./algo_trader
      args:
        LIB_IMAGE: algo_lib_local:latest
    image: algo_trader_local:latest
    depends_on:
      - algo_lib

  algo_api:
    build: ./algo_api
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=hU6GB8mupEtzgvXjrZQHKF
    volumes:
      - ./algo_api:/go/src/app
    working_dir: /go/src/app
    ports:
      - 8080:8080

  couchdb:
    image: couchdb:3.3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=hU6GB8mupEtzgvXjrZQHKF
    volumes:
      - couchdb_data:/opt/couchdb/data
    ports:
      - 5984:5984

volumes:
  couchdb_data: