# Use the official Node.js image as base
FROM node:lts

# Set the working directory in the container
WORKDIR /app

# Copy package.json and yarn.lock to the working directory
COPY package.json yarn.lock ./

# Install dependencies including react-scripts
RUN yarn install

# Copy the rest of your application code
COPY . .

# Expose the port on which your React application will run
EXPOSE 3000

# Command to run your React application
CMD ["yarn", "start"]
