name: Build and Deploy Lib

on:
  push:
    branches:
      - master
    paths:
      - "algo_lib/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t adaneri/algo_lib:latest algo_lib

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push adaneri/algo_lib:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker-compose -f docker-compose-deploy.yml pull
            docker-compose -f docker-compose-deploy.yml up -d --force-recreate lib_trading
